version: '3.4'

services:
  mhotelscore.globalwebsite:
    image: ${DOCKER_REGISTRY-}mhotelscoreglobalwebsite
    build:
      context: ./MoldovaHotelsCore.GlobalWebSite
      dockerfile: Dockerfile
    networks:
      - mhotelscore-network
  
  mhotelscore.bookingservice:
    image: ${DOCKER_REGISTRY-}mhotelscorebookingservice
    build:
      context: ./MoldovaHotelsCore.BookingService
      dockerfile: Dockerfile
    networks:
      - mhotelscore-network

  mhotelscore.searchservice:
    image: ${DOCKER_REGISTRY-}mhotelscoresearchservice
    build:
      context: ./MoldovaHotelsCore.SearchService
      dockerfile: Dockerfile
    networks:
      - mhotelscore-network
  
  mhotelscore.msssql:
    image: mcr.microsoft.com/mssql/server
    networks:
      - mhotelscore-network
    environment:
      SA_PASSWORD: "Serv1234*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

networks:
  mhotelscore-network:
    driver: bridge